# Generated by Django 3.1.7 on 2021-03-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder', models.TextField(default='')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('intro', models.TextField(default='')),
                ('numberOfEmploy', models.IntegerField(default=0)),
                ('connection_time', models.DateTimeField(auto_now_add=True)),
                ('detail_service', models.TextField(default='')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('detail_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='category.detailcategory')),
                ('detail_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.detailregion')),
                ('imageUrl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.image')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region')),
                ('sub_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.TextField(default='')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField(default=0)),
                ('Content', models.TextField(default='')),
                ('reviewResponse', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_question', to='users.user')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to='users.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(default='')),
                ('answer', models.TextField(default='')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField(default='')),
                ('which_info', models.CharField(default='', max_length=2)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'info',
            },
        ),
        migrations.CreateModel(
            name='Detail_Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder', models.TextField(default='')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'detail_image',
            },
        ),
    ]
