# Generated by Django 3.1.7 on 2021-03-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210325_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.TextField(default=''),
        ),
    ]
