# Generated by Django 3.1.7 on 2021-03-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='DetailCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('detail_name', models.TextField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'db_table': 'detail_category',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sub_name', models.TextField(default='')),
                ('detail_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.detailcategory')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
    ]
